# Generated by Django 6.1.1 on 2026-09-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance_unit',
            field=models.CharField(choices=[('km', 'Kilometres (km)'), ('mi', 'Miles (mi)')], default='km', max_length=2),
        ),
    ]
